### ISSUE TITLE
requirements.txt  里面版本号需要加一下啊

### ISSUE THREAD

**Issue by vTNT** [Jack614/saplatform#1]
rt

**Comment by Jack614** [comment]
ok,目前安装最新版的没什么问题

**Comment by vTNT** [comment]
https://github.com/Jack614/saplatform/blob/e6ecd6bb4aa07b2ea33bef10a9a5e1c1d8f1b819/requirements.txt      用这个里面的版本可以运行，  另外就是settings里面 base.py 要增加个配置
EMAIL_HOST_USER = ''  不然启动会报错   目前是这样

**Comment by Jack614** [comment]
谢谢，是这样的，因为是用自己的账号，所以放到gitignore了

**Comment by vTNT** [comment]
oo  haode
